### ISSUE TITLE
Add the ability to margin/padding to the different elements

### ISSUE THREAD

**Issue by dasmikko** [schibsted/tweet_ui#4]
It would be pretty nice to be able to add padding and margin to the different elements in the ui. 

To make it more flexible. :)

**Comment by kawa89** [comment]
Hi. Thanks for the request. I will probably won't make it more flexible for now, since my aim was to be 1-1 (or as close to 1-1) to the original https://github.com/twitter-archive/twitter-kit-android SDK.
I think you could achieve this by composing a widget yourself. Just copy-paste the code from TweetView widget and modify it.
