### ISSUE TITLE
EmbeddedTweetView with scrollable_positioned_list plugin

### ISSUE THREAD

**Issue by mwolffalonso** [schibsted/tweet_ui#62]
**Describe the bug**
When using twitter_ui EmbeddedTweetView or TweetView in conjunction with scrollable_positioned_list plugin the scrolling function works badly (erratically)
This happens in flutter 1.22.x not in 1.20.x.

**To Reproduce**
1. Get a list of tweets in json format
2. pass those the tweets to the EmbeddedTweetView inside the scrollable_positioned_list builder
3. use the scrollTo function in order to move programatically from one tweet to the next
4. See that the scrolling goes to the wrong position inside the list.

**Expected behavior**
Scroll to the correct position
This works fine if instead of TweetViews i use other things like a Card

**Smartphone (please complete the following information):**
 - Device: Any Android, Any iPhone
 - OS: Android / iOS
 - Version API 21+ / 10.3+ 

**Additional context**
Also opened an issue with the scrollable_positioned_list plugin

Example code

[scrollable_list_audioservice_v2.zip](https://github.com/schibsted/tweet_ui/files/5875800/scrollable_list_audioservice_v2.zip)

**Comment by mwolffalonso** [comment]
Hello @kawa89 do you think this is a bug from this plugin or from scrollable_positioned_list?

**Comment by kawa89** [comment]
In my opinion, it's not a problem with my plugin. In your example I see this behavior:
1. The app opens
2. Click on the `Start speaking button`
3. The app scrolls to the last item 49, but in a speedy way. It looks like it doesn't build all the items when it's scrolling down, just the last ones. Maybe to be efficient in some way. Let's assume the scroll was by 400 px (if all the items were built the scroll should be way longer because it's 49 tweets).
4. Click `pause` and `stop` buttons 
5. Scroll back up to the 1st position
6. Click again `Start speaking button`
7. You should be on the last item, but the app scrolls just by the remembered 400 px, like it didn't recalculate the distance correctly.

Additionally, I found out that If you:
1. The app opens
2. Click on the `Start speaking button`
3. The app scrolls to the last item 49
4. Click `pause` and `stop` buttons
5. Click again `Start speaking button` (without going back to top)
6. The app still tries to go down by the 400 px, but it should stay in place.

Have you tried using the ListView.builder and their `animateToPage` method?
